baseURL: https://danielbrennand.com
title: Daniel Brennand
theme: hugo-PaperMod

# Enable emojis in blog content
enableEmoji: true

params:
    author: Daniel Brennand
    comments: false
    ShowReadingTime: true
    ShowToc: true
    ShowShareButtons: false
    defaultTheme: auto
    cover:
        responsiveImages: true
        linkFullImages: false
    # Home info mode parameters
    homeInfoParams:
        Title: Hi, I'm Daniel Brennand 👋

    socialIcons:
        - name: github
          url: https://github.com/dbrennand
        - name: email
          url: bWFpbHRvOmNvbnRhY3RAZGFuaWVsYnJlbm5hbmQuY29tCg==
        - name: linkedin
          url: https://www.linkedin.com/in/daniel-brennand/

menu:
    main:
        - identifier: Blog
          name: Blog
          url: /blog
          weight: 10
        - identifier: Tags
          name: Tags
          url: /tags
          weight: 20
        - identifier: Archive
          name: Archive
          url: /archives
          weight: 30

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
