baseURL: https://dbren.uk
title: Daniel Brennand
theme:
  - hugo-PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Theme specific config
# https://github.com/adityatelange/hugo-PaperMod
params:
  env: production
  author: Daniel Brennand
  description: Daniel Brennand - Blog & Personal Website
  assets:
    disableHLJS: true
  keywords:
    - Blog
    - Personal Website
  defaultTheme: auto
  cover:
    responsiveImages: true
    linkFullImages: false
  comments: false
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  hidemeta: false
  # Home info mode parameters
  homeInfoParams:
    Title: Hi, I'm Daniel Brennand 👋
    Content: |
      Welcome to my blog! ✍

      I'm a Service Delivery Engineer 🛠 passionate about DevOps, self-hosting and developing open source software.

  socialIcons:
    - name: github
      url: https://github.com/dbrennand
    - name: email
      url: mailto:contact@danielbrennand.com
    - name: linkedin
      url: https://www.linkedin.com/in/dbrenuk
    - name: twitter
      url: https://twitter.com/dbrenuk

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog
      weight: 10
    - name: Search
      url: /search
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags
      weight: 30
    - identifier: Archive
      name: Archive
      url: /archives
      weight: 40

# Hugo config
enableRobotsTXT: true
# Enable emojis in blog content
enableEmoji: true
# https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: false
    # noClasses: false
    style: monokai
