baseURL: https://danielbrennand.com
title: Daniel Brennand
theme: hugo-PaperMod

# Theme specific config
# https://github.com/adityatelange/hugo-PaperMod
params:
  env: production
  author: Daniel Brennand
  description: Daniel Brennand - Blog | Personal Website
  keywords:
    - Blog
    - Personal Website
  defaultTheme: auto
  cover:
    responsiveImages: true
    linkFullImages: false
  comments: false
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  hidemeta: false
  # Home info mode parameters
  homeInfoParams:
    Title: Hi, I'm Daniel Brennand 👋
    Content: |
      Welcome to my blog where I write about self-hosting and different technologies 🖥️🥧👨‍💻

  socialIcons:
    - name: github
      url: https://github.com/dbrennand
    - name: email
      url: bWFpbHRvOmNvbnRhY3RAZGFuaWVsYnJlbm5hbmQuY29tCg==
    - name: linkedin
      url: https://www.linkedin.com/in/dbrenuk
    - name: twitter
      url: https://twitter.com/dbrenuk

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: Archive
      name: Archive
      url: /archives
      weight: 30

# Hugo config
enableRobotsTXT: true
# Enable emojis in blog content
enableEmoji: true

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
