---
baseURL: https://dbren.uk
theme:
  - hugo-bearblog
title: Daniel Brennand
author: Daniel Brennand
copyright: Copyright © 2026, Daniel Brennand.
enableRobotsTXT: true
enableEmoji: true

markup:
  highlight:
    style: tokyonight-day
    lineNos: true
    lineNumbersInTable: false
    codeFences: true

params:
  description: Daniel Brennand - Blog & Personal Website
  title: Daniel Brennand
  enablePostNavigator: true
